import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import {
  createMint,
  createAccount,
  mintTo,
  getAccount,
  TOKEN_PROGRAM_ID,
} from "@solana/spl-token";
import { assert } from "chai";

// Import IDL types — generated by `anchor build`
import type { VigilStaking } from "../target/types/vigil_staking";
import type { VigilChallenge } from "../target/types/vigil_challenge";
import type { BountyVault } from "../target/types/bounty_vault";

const DECIMALS = 6;
const TOKEN_MULTIPLIER = 10 ** DECIMALS;

describe("vigil-protocol", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const stakingProgram = anchor.workspace.VigilStaking as Program<VigilStaking>;
  const challengeProgram = anchor.workspace.VigilChallenge as Program<VigilChallenge>;
  const bountyProgram = anchor.workspace.BountyVault as Program<BountyVault>;

  const authority = provider.wallet as anchor.Wallet;
  const auditor = Keypair.generate();
  const challenger = Keypair.generate();

  let vigilMint: PublicKey;
  let authorityTokenAccount: PublicKey;
  let auditorTokenAccount: PublicKey;
  let challengerTokenAccount: PublicKey;
  let stakingVaultTokenAccount: PublicKey;
  let bountyVaultTokenAccount: PublicKey;

  let stakingConfigPda: PublicKey;
  let stakingConfigBump: number;
  let stakeInfoPda: PublicKey;
  let challengeConfigPda: PublicKey;
  let vaultConfigPda: PublicKey;
  let stakingVaultAuthority: PublicKey;
  let bountyVaultAuthority: PublicKey;

  before(async () => {
    // Airdrop SOL to test accounts
    const airdropAuditor = await provider.connection.requestAirdrop(
      auditor.publicKey,
      10 * LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(airdropAuditor);

    const airdropChallenger = await provider.connection.requestAirdrop(
      challenger.publicKey,
      10 * LAMPORTS_PER_SOL
    );
    await provider.connection.confirmTransaction(airdropChallenger);

    // Create SPL token mint (simulating $VIGIL)
    vigilMint = await createMint(
      provider.connection,
      (authority as any).payer,
      authority.publicKey,
      null,
      DECIMALS
    );

    // Create token accounts
    authorityTokenAccount = await createAccount(
      provider.connection,
      (authority as any).payer,
      vigilMint,
      authority.publicKey
    );

    auditorTokenAccount = await createAccount(
      provider.connection,
      (authority as any).payer,
      vigilMint,
      auditor.publicKey
    );

    challengerTokenAccount = await createAccount(
      provider.connection,
      (authority as any).payer,
      vigilMint,
      challenger.publicKey
    );

    // Mint tokens to auditor (10,000 for silver tier)
    await mintTo(
      provider.connection,
      (authority as any).payer,
      vigilMint,
      auditorTokenAccount,
      authority.publicKey,
      10_000 * TOKEN_MULTIPLIER
    );

    // Derive PDAs
    [stakingConfigPda, stakingConfigBump] = PublicKey.findProgramAddressSync(
      [Buffer.from("config")],
      stakingProgram.programId
    );

    [stakeInfoPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("stake"), auditor.publicKey.toBuffer()],
      stakingProgram.programId
    );

    [stakingVaultAuthority] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), stakingConfigPda.toBuffer()],
      stakingProgram.programId
    );

    [challengeConfigPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("challenge_config")],
      challengeProgram.programId
    );

    [vaultConfigPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault_config")],
      bountyProgram.programId
    );

    [bountyVaultAuthority] = PublicKey.findProgramAddressSync(
      [Buffer.from("bounty_vault_auth"), vaultConfigPda.toBuffer()],
      bountyProgram.programId
    );

    // Create vault token accounts (owned by PDAs)
    stakingVaultTokenAccount = await createAccount(
      provider.connection,
      (authority as any).payer,
      vigilMint,
      stakingVaultAuthority,
    );

    bountyVaultTokenAccount = await createAccount(
      provider.connection,
      (authority as any).payer,
      vigilMint,
      bountyVaultAuthority,
    );
  });

  // Test 1: SPL token mint setup (replaces Hardhat token name/symbol test)
  it("sets up $VIGIL SPL token mint", async () => {
    const mintInfo = await provider.connection.getParsedAccountInfo(vigilMint);
    const data = (mintInfo.value?.data as any)?.parsed?.info;
    assert.equal(data.decimals, DECIMALS);
    assert.equal(data.mintAuthority, authority.publicKey.toBase58());

    const auditorAccount = await getAccount(provider.connection, auditorTokenAccount);
    assert.equal(
      Number(auditorAccount.amount),
      10_000 * TOKEN_MULTIPLIER,
      "Auditor should have 10,000 tokens"
    );
  });

  // Test 2: Staking + tier tracking
  it("stakes tokens and tracks tier correctly", async () => {
    // Initialize staking
    await stakingProgram.methods
      .initialize()
      .accounts({
        config: stakingConfigPda,
        vigilTokenMint: vigilMint,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    // Stake 5,000 tokens (silver tier)
    const stakeAmount = new anchor.BN(5_000 * TOKEN_MULTIPLIER);
    await stakingProgram.methods
      .stake(stakeAmount)
      .accounts({
        config: stakingConfigPda,
        stakeInfo: stakeInfoPda,
        auditor: auditor.publicKey,
        auditorTokenAccount: auditorTokenAccount,
        vaultTokenAccount: stakingVaultTokenAccount,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .signers([auditor])
      .rpc();

    const stakeInfo = await stakingProgram.account.stakeInfo.fetch(stakeInfoPda);
    assert.equal(stakeInfo.amount.toNumber(), 5_000 * TOKEN_MULTIPLIER);
    assert.equal(stakeInfo.isRegistered, true);

    const config = await stakingProgram.account.stakingConfig.fetch(stakingConfigPda);
    assert.equal(config.totalStakers.toNumber(), 1);
  });

  // Test 3: Tier upgrade
  it("upgrades tier when more tokens are staked", async () => {
    // Stake 5,000 more tokens (total 10,000 — still silver, approaching gold)
    const additionalStake = new anchor.BN(5_000 * TOKEN_MULTIPLIER);
    await stakingProgram.methods
      .stake(additionalStake)
      .accounts({
        config: stakingConfigPda,
        stakeInfo: stakeInfoPda,
        auditor: auditor.publicKey,
        auditorTokenAccount: auditorTokenAccount,
        vaultTokenAccount: stakingVaultTokenAccount,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .signers([auditor])
      .rpc();

    const stakeInfo = await stakingProgram.account.stakeInfo.fetch(stakeInfoPda);
    assert.equal(
      stakeInfo.amount.toNumber(),
      10_000 * TOKEN_MULTIPLIER,
      "Total staked should be 10,000"
    );
  });

  // Test 4: Challenge creation + resolution with slash distribution
  it("creates challenge, resolves with slash (60/20/20)", async () => {
    // Initialize challenge program
    await challengeProgram.methods
      .initialize()
      .accounts({
        config: challengeConfigPda,
        stakingProgram: stakingProgram.programId,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    // Create challenge
    const [challengePda] = PublicKey.findProgramAddressSync(
      [Buffer.from("challenge"), new anchor.BN(0).toArrayLike(Buffer, "le", 8)],
      challengeProgram.programId
    );

    const proofHash = Buffer.alloc(32);
    proofHash.write("test-proof-hash");

    await challengeProgram.methods
      .createChallenge("test-skill-001", [...proofHash] as any)
      .accounts({
        config: challengeConfigPda,
        challenge: challengePda,
        auditorStakeInfo: stakeInfoPda,
        challenger: challenger.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([challenger])
      .rpc();

    const challenge = await challengeProgram.account.challenge.fetch(challengePda);
    assert.equal(challenge.challenger.toBase58(), challenger.publicKey.toBase58());
    assert.equal(challenge.auditor.toBase58(), auditor.publicKey.toBase58());

    // Resolve challenge with slash
    await challengeProgram.methods
      .resolve(true, new anchor.BN(1_000 * TOKEN_MULTIPLIER))
      .accounts({
        config: challengeConfigPda,
        challenge: challengePda,
        authority: authority.publicKey,
      })
      .rpc();

    // Execute slash on staking program
    const slashAmount = new anchor.BN(1_000 * TOKEN_MULTIPLIER);
    await stakingProgram.methods
      .slash(slashAmount)
      .accounts({
        config: stakingConfigPda,
        stakeInfo: stakeInfoPda,
        authority: authority.publicKey,
        vaultTokenAccount: stakingVaultTokenAccount,
        challengerTokenAccount: challengerTokenAccount,
        bountyTokenAccount: bountyVaultTokenAccount,
        vaultAuthority: stakingVaultAuthority,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();

    // Verify distribution: 60% to challenger, 20% to bounty, 20% burned
    const challengerAccount = await getAccount(provider.connection, challengerTokenAccount);
    assert.equal(
      Number(challengerAccount.amount),
      600 * TOKEN_MULTIPLIER,
      "Challenger should receive 60% (600 tokens)"
    );

    const bountyAccount = await getAccount(provider.connection, bountyVaultTokenAccount);
    assert.equal(
      Number(bountyAccount.amount),
      200 * TOKEN_MULTIPLIER,
      "Bounty vault should receive 20% (200 tokens)"
    );

    // Auditor stake reduced by 1000
    const stakeInfo = await stakingProgram.account.stakeInfo.fetch(stakeInfoPda);
    assert.equal(
      stakeInfo.amount.toNumber(),
      9_000 * TOKEN_MULTIPLIER,
      "Auditor stake should be reduced to 9,000"
    );
  });

  // Test 5: BountyVault deposit + claim
  it("deposits to bounty vault and claims reward", async () => {
    // Initialize bounty vault
    await bountyProgram.methods
      .initialize()
      .accounts({
        config: vaultConfigPda,
        vigilTokenMint: vigilMint,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    // Mint tokens to authority for deposit
    await mintTo(
      provider.connection,
      (authority as any).payer,
      vigilMint,
      authorityTokenAccount,
      authority.publicKey,
      5_000 * TOKEN_MULTIPLIER
    );

    // Deposit to vault
    await bountyProgram.methods
      .deposit(new anchor.BN(1_000 * TOKEN_MULTIPLIER))
      .accounts({
        config: vaultConfigPda,
        depositor: authority.publicKey,
        depositorTokenAccount: authorityTokenAccount,
        vaultTokenAccount: bountyVaultTokenAccount,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .rpc();

    // Create reward for challenger
    const [rewardPda] = PublicKey.findProgramAddressSync(
      [Buffer.from("reward"), new anchor.BN(0).toArrayLike(Buffer, "le", 8)],
      bountyProgram.programId
    );

    await bountyProgram.methods
      .createReward(challenger.publicKey, new anchor.BN(500 * TOKEN_MULTIPLIER), new anchor.BN(0))
      .accounts({
        config: vaultConfigPda,
        reward: rewardPda,
        authority: authority.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    // Challenger claims reward
    await bountyProgram.methods
      .claim()
      .accounts({
        config: vaultConfigPda,
        reward: rewardPda,
        recipient: challenger.publicKey,
        recipientTokenAccount: challengerTokenAccount,
        vaultTokenAccount: bountyVaultTokenAccount,
        vaultAuthority: bountyVaultAuthority,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .signers([challenger])
      .rpc();

    const reward = await bountyProgram.account.bountyReward.fetch(rewardPda);
    assert.equal(reward.claimed, true);

    // Challenger should now have 600 (from slash) + 500 (from bounty) = 1100 tokens
    const challengerAccount = await getAccount(provider.connection, challengerTokenAccount);
    assert.equal(
      Number(challengerAccount.amount),
      1_100 * TOKEN_MULTIPLIER,
      "Challenger should have 1,100 tokens total"
    );
  });

  // Test 6: Unstake cooldown enforcement
  it("enforces unstake cooldown period", async () => {
    // Request unstake
    await stakingProgram.methods
      .requestUnstake(new anchor.BN(1_000 * TOKEN_MULTIPLIER))
      .accounts({
        stakeInfo: stakeInfoPda,
        auditor: auditor.publicKey,
      })
      .signers([auditor])
      .rpc();

    const stakeInfo = await stakingProgram.account.stakeInfo.fetch(stakeInfoPda);
    assert.equal(stakeInfo.unstakeRequestAmount.toNumber(), 1_000 * TOKEN_MULTIPLIER);
    assert.isAbove(stakeInfo.unstakeRequestTime.toNumber(), 0);

    // Try to unstake immediately — should fail
    try {
      await stakingProgram.methods
        .unstake()
        .accounts({
          config: stakingConfigPda,
          stakeInfo: stakeInfoPda,
          auditor: auditor.publicKey,
          auditorTokenAccount: auditorTokenAccount,
          vaultTokenAccount: stakingVaultTokenAccount,
          vaultAuthority: stakingVaultAuthority,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .signers([auditor])
        .rpc();
      assert.fail("Should have thrown CooldownNotElapsed error");
    } catch (err: any) {
      assert.include(err.toString(), "CooldownNotElapsed");
    }
  });
});
